apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: onjr5kkkn-go
  janus-idp.io/tekton: onjr5kkkn-go
  backstage.io/kubernetes-id: onjr5kkkn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: onjr5kkkn-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
