apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: onjr5kkkn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: onjr5kkkn-go 
  name: onjr5kkkn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: onjr5kkkn-go 
